# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBcCIy9i8DYUdALGXTPEC-DnEZ_2ufVl
"""

import pandas as pd
baza={
    "Fish":[ "Vini junior" , "Jude Beliingham" , "Klian Mbappe", "Fede Valverde", "Rodrigo Goes", "Arda Guler", "Toni Rudiger", "Eder Militao", "Luka Modrich", "Ferland Mendy" ],
    "Yoshi":[ "24" , "21" , "25", "26", "23", "19", "29", "30", "38", "25"  ],
    "Jinsi":[ "erkak", "erkak", "erkak" , "erkak", "erkak", "erkak", "erkak", "erkak", "erkak", "erkak" ],
    "Maktabi":[ "7-maktab" , "5-maktab", "9-maktab", "8-maktab", "11-maktab", "15-maktab", "22-maktab", "3-maktab", "10-maktab", "23-maktab" ],
    "Manzili":[ "Madrid" ,  "London", "Paris", "Madrid", "Rio da janero", "Istanbul", "Berlin", "Brazil", "Madrid", "Marserl"  ],
    "Tel raqami":[ "99 777 77 77" , "95 555 55 55","99 999 99 99", "99 888 88 88", "91 111 11 11", "99 151 15 15", "99 222 22 22", "93 333 33 33", "90 101 10 10", "99 232 23 23" ]

}

db=pd.DataFrame(baza)
print(db)

filtr=db[db['Manzili']=="Madrid"]
print(filtr)

filtr=db[(db['Manzili']=="Madrid") & (db["Yoshi"]>"25")]
print(filtr)